/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Sohan
 */
public class adminloginpage extends javax.swing.JFrame {

 
    /**
     * Creates new form login
     */
    public adminloginpage() {
        initComponents();
      //  jPanel2.setBackground(new Color(0,0,0,120));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextusername = new javax.swing.JTextField();
        jTxtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        hidelebel = new javax.swing.JLabel();
        seelebel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 341, -1, -1));

        jPanel3.setBackground(new java.awt.Color(70, 72, 235));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sohan\\Downloads\\primary school\\logo.png")); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 260, 250));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 410));

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(70, 72, 235));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sohan\\Downloads\\primary school\\key.png")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 30, 30));

        jTextusername.setText("Username");
        jTextusername.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEtchedBorder()));
        jTextusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextusernameFocusGained(evt);
            }
        });
        jPanel2.add(jTextusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 190, 30));

        jTxtPassword.setText("Password");
        jTxtPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEtchedBorder()));
        jTxtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtPasswordFocusGained(evt);
            }
        });
        jPanel2.add(jTxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 190, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sohan\\Downloads\\primary school\\usericon.jpg")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        hidelebel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sohan\\Downloads\\primary school\\key1.png")); // NOI18N
        hidelebel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidelebelMouseClicked(evt);
            }
        });
        jPanel2.add(hidelebel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, 30));

        seelebel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sohan\\Downloads\\primary school\\eye.png")); // NOI18N
        seelebel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seelebelMouseClicked(evt);
            }
        });
        jPanel2.add(seelebel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("Username:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setText("Password:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jButton2.setBackground(new java.awt.Color(70, 72, 235));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 80, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 360, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String username = jTextusername.getText();
        String pass = jTxtPassword.getText();

        if(username.equals("admin")&&pass.equals("1234"))
        {
            admininterpage m = new  admininterpage();
            this.hide();
            m.setVisible(true);
        }
        else if(username.isEmpty()||pass.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "username or pass should not be empty");
        }
        else
        {
            JOptionPane.showMessageDialog(this,"user or pass wrong");
            jTextusername.setText("");
            jTxtPassword.setText("");
            jTextusername.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTxtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtPasswordFocusGained
      jTxtPassword.setText("");
        

// TODO add your handling code here:
    }//GEN-LAST:event_jTxtPasswordFocusGained

    private void jTextusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextusernameFocusGained
      jTextusername.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jTextusernameFocusGained

    private void hidelebelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidelebelMouseClicked
     
       
        
       jTxtPassword.setEchoChar((char)0);  
    hidelebel.setVisible(false);
     seelebel.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_hidelebelMouseClicked

    private void seelebelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seelebelMouseClicked
     
          jTxtPassword.setEchoChar('*');  
     hidelebel.setVisible(true);
     seelebel.setVisible(false); 
//TODO add your handling code here:// TODO add your handling code here:
    }//GEN-LAST:event_seelebelMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    mainpage e = new mainpage();
        this.hide();
        e.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminloginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminloginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminloginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminloginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminloginpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hidelebel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextusername;
    private javax.swing.JPasswordField jTxtPassword;
    private javax.swing.JLabel seelebel;
    // End of variables declaration//GEN-END:variables
}
